"""Engine adapters are imported only when selected."""

ENGINE_INFO = {
    "pocket": {
        "label": "Pocket TTS",
        "summary": "Compact voice cloning with INT8-optimized CPU inference.",
        "default_voice": "alba",
        "default_language": "english",
        "sample_rate": 24000,
        "languages": [
            "english",
            "french_24l",
            "spanish_24l",
            "german_24l",
            "italian_24l",
            "portuguese_24l",
        ],
        "voices": [
            "alba",
            "giovanni",
            "lola",
            "juergen",
            "rafael",
            "estelle",
            "anna",
            "azelma",
            "bill_boerst",
            "caro_davy",
            "charles",
            "cosette",
            "eponine",
            "eve",
            "fantine",
            "george",
            "jane",
            "javert",
            "jean",
            "marius",
            "mary",
            "michael",
            "paul",
            "peter_yearsley",
            "stuart_bell",
            "vera",
        ],
    },
    "kokoro": {
        "label": "Kokoro",
        "summary": "Expressive 82M-parameter voices across nine accents and languages.",
        "default_voice": "af_heart",
        "default_language": "a",
        "sample_rate": 24000,
        "languages": ["a", "b", "e", "f", "h", "i", "j", "p", "z"],
        "voices": [
            "af_alloy",
            "af_aoede",
            "af_bella",
            "af_heart",
            "af_jessica",
            "af_kore",
            "af_nicole",
            "af_nova",
            "af_river",
            "af_sarah",
            "af_sky",
            "am_adam",
            "am_echo",
            "am_eric",
            "am_fenrir",
            "am_liam",
            "am_michael",
            "am_onyx",
            "am_puck",
            "am_santa",
            "bf_alice",
            "bf_emma",
            "bf_isabella",
            "bf_lily",
            "bm_daniel",
            "bm_fable",
            "bm_george",
            "bm_lewis",
            "ef_dora",
            "em_alex",
            "em_santa",
            "ff_siwis",
            "hf_alpha",
            "hf_beta",
            "hm_omega",
            "hm_psi",
            "if_sara",
            "im_nicola",
            "jf_alpha",
            "jf_gongitsune",
            "jf_nezumi",
            "jf_tebukuro",
            "jm_kumo",
            "pf_dora",
            "pm_alex",
            "pm_santa",
            "zf_xiaobei",
            "zf_xiaoni",
            "zf_xiaoxiao",
            "zf_xiaoyi",
            "zm_yunjian",
            "zm_yunxi",
            "zm_yunxia",
            "zm_yunyang",
        ],
    },
    "piper": {
        "label": "Piper",
        "summary": "Fast, dependable ONNX synthesis with a bundled US voice.",
        "default_voice": "en_US-lessac-medium",
        "default_language": "en-US",
        "sample_rate": 22050,
        "languages": ["en-US"],
        "voices": ["en_US-lessac-medium"],
    },
    "kitten": {
        "label": "Kitten TTS",
        "summary": "Tiny 15M-parameter ONNX model with eight English voices.",
        "default_voice": "Leo",
        "default_language": "en",
        "sample_rate": 24000,
        "languages": ["en"],
        "voices": ["Bella", "Jasper", "Luna", "Bruno", "Rosie", "Hugo", "Kiki", "Leo"],
    },
    "supertonic": {
        "label": "Supertonic 3",
        "summary": "High-speed multilingual synthesis at studio-grade 44.1 kHz.",
        "default_voice": "M1",
        "default_language": "en",
        "sample_rate": 44100,
        "languages": [
            "en",
            "ko",
            "ja",
            "ar",
            "bg",
            "cs",
            "da",
            "de",
            "el",
            "es",
            "et",
            "fi",
            "fr",
            "hi",
            "hr",
            "hu",
            "id",
            "it",
            "lt",
            "lv",
            "nl",
            "pl",
            "pt",
            "ro",
            "ru",
            "sk",
            "sl",
            "sv",
            "tr",
            "uk",
            "vi",
            "na",
        ],
        "voices": ["M1", "M2", "M3", "M4", "M5", "F1", "F2", "F3", "F4", "F5"],
    },
    "breeze": {
        "label": "Breeze TTS 2",
        "summary": "English and Chinese voice design. Research/non-commercial use only.",
        "default_voice": None,
        "default_language": "en",
        "sample_rate": 24000,
        "languages": ["en", "zh"],
        "voices": [],
        "voice_input": "description",
    },
    "fish": {
        "label": "Fish Audio S2-Pro",
        "summary": "Built with Fish Audio. Multilingual speech with inline style cues. Research/non-commercial use only.",
        "default_voice": None,
        "default_language": "en",
        "sample_rate": 44100,
        "languages": [
            "zh",
            "en",
            "ja",
            "ko",
            "es",
            "pt",
            "ar",
            "ru",
            "fr",
            "de",
            "sv",
            "it",
            "tr",
            "no",
            "nl",
            "cy",
            "eu",
            "ca",
            "da",
            "gl",
            "ta",
            "hu",
            "fi",
            "pl",
            "et",
            "hi",
            "la",
            "ur",
            "th",
            "vi",
            "jw",
            "bn",
            "yo",
            "sl",
            "cs",
            "sw",
            "nn",
            "he",
            "ms",
            "uk",
            "id",
            "kk",
            "bg",
            "lv",
            "my",
            "tl",
            "sk",
            "ne",
            "fa",
            "af",
            "el",
            "bo",
            "hr",
            "ro",
            "sn",
            "mi",
            "yi",
            "am",
            "be",
            "km",
            "is",
            "az",
            "sd",
            "br",
            "sq",
            "ps",
            "mn",
            "ht",
            "ml",
            "sr",
            "sa",
            "te",
            "ka",
            "bs",
            "pa",
            "lt",
            "kn",
            "si",
            "hy",
            "mr",
            "as",
            "gu",
            "fo",
        ],
        "voices": [],
        "voice_input": "style",
    },
}
